### PR TITLE
Block syntax to parametrize action's url

### PR DESCRIPTION
**Pull request by dpisarewski**

### CODE REVIEW

**Comment by janfoeh** [comment]
Hi Dieter,

thanks for the PR!

I haven't had much sleep, so forgive me if I get this wrong, but I think you could already achieve what you are trying to do with the status quo ante. That's what the changes to `url` [last week](https://github.com/janfoeh/apidiesel/commit/e796e535abfb3bc85a1baee7c82f560606740ba1) were for — to change the endpoint URL depending on action parameters.

[Here's an example](https://github.com/janfoeh/doxieland/blob/master/lib/doxieland/actions/get_scan.rb) of how I use it:

``` ruby
module Doxieland
  module Actions
    class GetScan < ::Apidiesel::Action
      use Apidiesel::Handlers::ActionResponseProcessor
      use Handlers::FileRequest

      url ->(base_url, request) {
        base_url.path = request.parameters.delete(:path)

        base_url
      }

      http_method :get

      expects do
        string :path
      end
    end
  end
end
```

Is there anything your PR covers that this does not?

Cheers,
Jan

**Comment by dpisarewski** [comment]
Hi Jan, you are right. 
We had the version 0.9 installed when I started to work on this. At first I patched the gem with my changes. Later I forked the repository and saw that we use an older version. But I guess my changes could make this feature a bit more flexible since the parameters are stored in action(1 argument required for the block) and the block can return options for URI or a string like before.

**Comment by janfoeh** [comment]
That's actually quite similar to how I did it at first. But I think of `Action` as more of a abstract description of an API endpoint - a "class" for an API request if you will, with the `Request` being the "class instance".

So since it's the `Request` object that contains all the parameters of the actual current request, it made sense to me that the final URL should be an attribute on it as well.

That still makes sense to me, and I would prefer to keep it as-is. What I'm not happy with is that blocks are unnecessarily complex and ugly for the simple use case of "include a parameter here in the url"

What do you think about introducing an option for simple substitutions, as in:

``` ruby
module Actions
  class GetUsers < Apidiesel::Action
    url path: "/users/%{username}"

    expects do
      string :username
    end

    responds_with do
      objects :users, wrapped_in: MyUserModel
    end
  end
end
```

?

**Comment by janfoeh** [comment]
As an aside, I promise to add release notes to new versions from now on. That should make it easier to keep up if you're watching this repo - provided you don't want to stick with your own fork of course.

**Comment by dpisarewski** [comment]
> What I'm not happy with is that blocks are unnecessarily complex and ugly for the simple use case of "include a parameter here in the url"
> 
> What do you think about introducing an option for simple substitutions, as in:

It looks pretty, but will be more complex and not as flexible as a block. I would stick to a block because every ruby developer is familiar with it, so there is no need to learn anything extra. However I would expect the block takes parameters or an action instance as argument. I think, the user should not know about internal implementation such as Request when defining an action.

**Comment by Maddin2Code** [comment]
Hi. I tried to implement it like Jan explained the implementation for V 0.12. 

My findings:
- the `path` parameter has to be named in `format_parameters`, otherwise it is not available in request.parameters in url lambda
- if you put it into `format_parameters` it becomes available but goes also into the request payload
- the delete (`request.parameters.delete(:path)`) is not changing `request.parameters` outside of the lambda

Could be good to use the `expects` block to define which parameter should be ignored for the request payload using a simple option. Other thoughts?

**Comment by janfoeh** [comment]
@dpisarewski 

> It looks pretty, but will be more complex and not as flexible as a block.

The plan is to offer that as an alternative, not to replace blocks. Make simple things simple and complex things possible, and all that.

> However I would expect the block takes parameters or an action instance as argument. I think, the user should not know about internal implementation such as Request when defining an action.

`Request` isn't an internal implementation detail — it's the return value of every API call.

@Maddin2Code yeah, that part is messy. I think I'd like to introduce a distinction between _arguments_ to the action and _parameters_. The first one will simply be a verbatim copy of everything you gave the action, and only the latter will be processed according to the validations and `format_parameter`.

Good call on skipping arguments as payload — I'll introduce a `submit: false` flag. However, this flag will have no effect when you use `format_parameters`. It'll still submit everything you return there.

**Comment by janfoeh** [comment]
There's a new release out: [v0.13](https://github.com/janfoeh/apidiesel/releases/tag/v0.13).

**Comment by Maddin2Code** [comment]
Thank you Jan, we will try it out tomorrow!

**Comment by dpisarewski** [comment]
@janfoeh awesome!

**Pull request closed without merging**
